#:kivy 1.11.1

<SnakeGame>
    snake: Jake
    food: appl

    Snake:
        id: Jake
        pos: self.set_pos(root.width, root.height)

    Food:
        id: appl
        pos: self.random_pos(root.width, root.height)


<Snake>
    size: 40, 40
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size


<Food>
    size: 40, 40
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size